# Generated by Django 2.1 on 2018-08-03 03:25

import cyoa.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('result_type', models.CharField(choices=[(cyoa.models.ChoiceResultType('Question'), 'Question'), (cyoa.models.ChoiceResultType('Recommendation'), 'Recommendation')], default=cyoa.models.ChoiceResultType('Question'), max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.BooleanField(default=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='recommendation',
            name='available_on',
            field=models.ManyToManyField(to='cyoa.Source'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='cyoa.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='result_question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_question', to='cyoa.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='result_recommendation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_recommendation', to='cyoa.Recommendation'),
        ),
    ]
