# Generated by Django 2.1.1 on 2018-09-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyoa', '0002_remove_recommendation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
