# Generated by Django 2.1.1 on 2018-11-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyoa', '0004_recommendation_drawer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='drawer',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
